<a href="https://colab.research.google.com/github/ArduousBrain/Deep-Learning-PS/blob/master/perceptron_base_extra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
class Perceptron(object):

  def __init__(self, no_of_inputs, threshold=5, learning_rate=0.01):
    self.threshold = threshold
    self.learning_rate = learning_rate
    self.weights = np.zeros(no_of_inputs + 1)

  def predict(self, inputs):
    summation = np.dot(inputs, self.weights[1:]) + self.weights[0]

    if summation>0:
      activation = 1
    else:
      activation = 0
    
    return activation

  def train(self, training_inputs, labels):
    for _ in range(self.threshold):
      for inputs, label in zip(training_inputs, labels):
        prediction = self.predict(inputs)
        self.weights[1:] += self.learning_rate * (label - prediction) * inputs
        self.weights[0] += self.learning_rate * (label - prediction)
        print(self.weights)


In [3]:
training_inputs = []
training_inputs.append(np.array([1,1]))
training_inputs.append(np.array([1,0]))
training_inputs.append(np.array([0,1]))
training_inputs.append(np.array([0,0]))

labels = np.array([1,0,0,0])

perceptron = Perceptron(2)
perceptron.train(training_inputs, labels)

inputs = np.array([1,1])
print(perceptron.predict(inputs))

[0.01 0.01 0.01]
[0.   0.   0.01]
[-0.01  0.    0.  ]
[-0.01  0.    0.  ]
[0.   0.01 0.01]
[-0.01  0.    0.01]
[-0.01  0.    0.01]
[-0.01  0.    0.01]
[0.   0.01 0.02]
[-0.01  0.    0.02]
[-0.02  0.    0.01]
[-0.02  0.    0.01]
[-0.01  0.01  0.02]
[-0.01  0.01  0.02]
[-0.02  0.01  0.01]
[-0.02  0.01  0.01]
[-0.01  0.02  0.02]
[-0.02  0.01  0.02]
[-0.02  0.01  0.02]
[-0.02  0.01  0.02]
1
